[project]
name = "innowise-project"
version = "0.1.0"
description = "Innowise laboratory project"

dependencies = []

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"